[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build:staging"