# Generated by Django 3.2 on 2024-06-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_comment_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
